model:
  name: "gemini-2.5-flash-lite"
  project: "bqsqltesting"
  location: "europe-west1"
  parameters:
    temperature: 0.5
    top_p: 0.95
    max_output_tokens: 1024
  safety_settings:
    HARM_CATEGORY_HATE_SPEECH: "OFF"
    HARM_CATEGORY_DANGEROUS_CONTENT: "OFF"
    HARM_CATEGORY_SEXUALLY_EXPLICIT: "OFF"
    HARM_CATEGORY_HARASSMENT: "OFF"

vertex_ai_search:
  datastore_id: "projects/bqsqltesting/locations/global/collections/default_collection/dataStores/bc_catalogue"
